<?php

namespace Duf\AggregatorBundle\Entity\Repository;

use Duf\AdminBundle\Entity\Repository\DufAdminRepository;

/**
 * AggregatorAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AggregatorAccountRepository extends DufAdminRepository
{
}
